# Generated by Django 6.0.6 on 2026-06-17 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_jobs', to='accounts.workerprofile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='accounts.workerprofile'),
        ),
    ]
