# Generated by Django 6.0.6 on 2026-06-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customerprofile_last_seen_supportchat_supportmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='service_type',
            field=models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('ac_repair', 'AC Repair'), ('mobile_repair', 'Mobile Repair'), ('carpenter', 'Carpenter'), ('painter', 'Painter'), ('cleaning_service', 'Cleaning Service')], max_length=50),
        ),
    ]
